service: webtoonguru-thumbnail-modifier-jjy
frameworkVersion: '3'
package:
  exclude:
    - node_modules/**
    - venv/**

provider:
  name: aws
  runtime: python3.8
  region: ap-northeast-2
  apiName: webtoonguru-thumbnail-modifier-jjy
  endpointType: EDGE
  apiGateway:
    binaryMediaTypes:
      - "*/*"
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
          Resource: 'arn:aws:s3:::webtoonguru-thumbnail-jjy/*'

functions:
  thumbnailModifier:
    handler: handler.thumbnail_modifier
    events:
      - http:
          path: /
          method: get
  refererCheck:
    handler: referer_check.referer_check
    events:
      - http:
          path: /
          method: post



custom:
  pythonRequirements:
    dockerizePip: "non-linux"
  customDomain:
    domainName: thumbnail.webtoon.guru
    basePath: ''
    createRoute53Record: true
    # stage: ${self:provider.stage}
  serverless-offline:
    # httpsProtocol: "dev-certs"
    httpPort: 6000
    # stageVariables:
    #   foo: "bar"
  # serverless-offline-watcher:
  #   - path: handler.py
  #     command: sls offline end
  #     # command: echo "changed"

plugins:
  - serverless-offline
  # - serverless-offline-watcher
  - serverless-python-requirements
  - serverless-domain-manager
